<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findByWeightMin()
    {
        $query = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Product','p')
            ->orderBy('p.weight', 'ASC');

        return $query->getQuery()->getResult();
    }

    public function findByWeightMax()
    {
        $query = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Product','p')
            ->orderBy('p.weight', 'DESC');

        return $query->getQuery()->getResult();
    }

    public function findByPricetMin()
    {
        $query = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Product','p')
            ->orderBy('p.price', 'ASC');

        return $query->getQuery()->getResult();
    }

    public function findByPriceMax()
    {
        $query = $this->_em->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Product','p')
            ->orderBy('p.price', 'DESC');

        return $query->getQuery()->getResult();
    }
}
